# Generated by Django 5.2.5 on 2025-08-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordrecord',
            name='url',
        ),
    ]
